---

- hosts: all
  connection: winrm
  vars:
    ansible_winrm_server_cert_validation: ignore
    ansible_winrm_transport: credssp
  pre_tasks:
  - name: set fact for ou name
    set_fact:
      ou_name: "{{ app }}"
    when: app is defined

  roles:
  - pharriso.windows.windows_ou
