secgroup_rules:
- name: ssh
  protocol: Tcp
  destination_port_range: 22
  access: Allow
  priority: 101
  direction: Inbound
- name: web
  protocol: Tcp
  destination_port_range: 80
  access: Allow
  priority: 102
  direction: Inbound
- name: winrm
  protocol: Tcp
  destination_port_range: 5986
  access: Allow
  priority: 103
  direction: Inbound
- name: rdp
  protocol: Tcp
  destination_port_range: 3389
  access: Allow
  priority: 104
  direction: Inbound
- name: f5_mgmt
  protocol: Tcp
  destination_port_range: 8443
  access: Allow
  priority: 105
  direction: Inbound
- name: https
  protocol: Tcp
  destination_port_range: 443
  access: Allow
  priority: 106
  direction: Inbound
- name: internal
  protocol: '*'
  access: Allow
  priority: 107
  destination_port_range: '*'
  destination_address_prefix: VirtualNetwork
- name: pcsd
  protocol: Tcp
  destination_port_range: 2224
  access: Allow
  priority: 108
  direction: Inbound
- name: postgresql
  protocol: Tcp
  destination_port_range: 5432
  access: Allow
  priority: 109
  direction: Inbound
